version: '3'

services:
  nava_backend:
    build: ./
    container_name: nava-backend
    restart: on-failure
    command: npm run dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 4000:4000
    depends_on:
      - nava_backend_db

  nava_backend_db:
    image: mysql:8.0.31
    container_name: nava-backend-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .development.env
    ports:
      - '3306:3306'
    volumes:
      - mysql_backend:/data/db

  nava-backend-adminer:
    image: adminer
    container_name: nava-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - nava_backend_db

volumes:
  mysql_backend:
